export const lessons = [
  {
    id: "1",
    title: "Lesson 1",
    words: [
      {
        english: "Abandon",
        example1: "He abandoned the old house",
        chinese: "放弃",
        example2: "他抛弃了那座老房子",
        spanish: "Abandonar",
        example3: "Él abandonó la casa vieja",
        french: "Abandonner",
        example4: "Il a abandonné la vieille maison",
        arabic: "تَرَكَ",
        example5: "تَرَكَ الْمَنْزِلَ الْقَدِيمَ",
        id: "1-1",
      },
      {
        english: "Keen",
        example1: "She is keen to learn new skills",
        chinese: "敏锐的",
        example2: "她很渴望学习新技能",
        spanish: "Interesada",
        example3: "Ella está deseosa de aprender nuevas habilidades",
        french: "Passionnée",
        example4: "Elle est désireuse d’apprendre de nouvelles compétences",
        arabic: "حَادّ",
        example5: "هي مُتَحَمِّسَةٌ لِتَعَلُّمِ مَهَارَاتٍ جَدِيدَةٍ",
        id: "1-2",
      },
      {
        english: "Jealous",
        example1: "He felt jealous of his brother’s success.",
        chinese: "嫉妒的",
        example2: "他对他哥哥的成功感到嫉妒",
        spanish: "Celosa",
        example3: "Él sintió envidia del éxito de su hermano",
        french: "Jalouse",
        example4: "Il a ressenti de la jalousie face au succès de son frère",
        arabic: "غَيُور",
        example5: "شَعَرَ بِالغِيرَةِ مِن نَجَاحِ أَخِيهِ",
        id: "1-3",
      },
      {
        english: "Tact",
        example1: "She handled the problem with tact.",
        chinese: "机智",
        example2: "她机智地处理了这个问题",
        spanish: "Tacto",
        example3: "Ella manejó el problema con tacto",
        french: "Tact",
        example4: "Elle a géré le problème avec tact",
        arabic: "لَبَاقَة",
        example5: "تَعَامَلَتْ مَعَ المُشْكِلَةِ بِدِقَّةٍ وَحِكْمَةٍ",
        id: "1-4",
      },
      {
        english: "Oath",
        example1: "He took an oath to tell the truth.",
        chinese: "誓言",
        example2: "他宣誓要说实话",
        spanish: "Juramento",
        example3: "Él juró decir la verdad",
        french: "Serment",
        example4: "Il a prêté serment de dire la vérité",
        arabic: "قَسَم",
        example5: "أَدَّى قَسَمًا لِيَقُولَ الحَقَّ",
        id: "1-5",
      },
      {
        english: "Vacant",
        example1: "The seat next to her was vacant.",
        chinese: "空缺",
        example2: "她旁边的座位是空的",
        spanish: "Vacante",
        example3: "El asiento a su lado estaba vacío",
        french: "Vacante",
        example4: "Le siège à côté d’elle était vide",
        arabic: "شَاغِر",
        example5: "كَانَ المَقْعَدُ بِجَانِبِهَا فَارِغًا",
        id: "1-6",
      },
      {
        english: "Hardship",
        example1: "They suffered hardship during the war.",
        chinese: "困难",
        example2: "他们在战争中遭受了苦难",
        spanish: "Privación",
        example3: "Ellos sufrieron dificultades durante la guerra",
        french: "Épreuves",
        example4: "Ils ont souffert de difficultés pendant la guerre",
        arabic: "مَشَقَّة",
        example5: "عَانَوْا مِنَ المَشَقَّةِ خِلَالَ الحَرْبِ",
        id: "1-7",
      },
      {
        english: "Gallant",
        example1: "The gallant soldier saved his friend.",
        chinese: "英勇",
        example2: "那个英勇的士兵救了他的朋友",
        spanish: "Galante",
        example3: "El soldado valiente salvó a su amigo",
        french: "Galante",
        example4: "Le soldat vaillant a sauvé son ami",
        arabic: "شُجَاع",
        example5: "أَنْقَذَ الجُنْدِيُّ الشُّجَاعُ صَدِيقَهُ",
        id: "1-8",
      },
      {
        english: "Data",
        example1: "The scientist collected new data.",
        chinese: "数据",
        example2: "科学家收集了新的数据",
        spanish: "Datos",
        example3: "El científico recopiló nuevos datos",
        french: "Données",
        example4: "Le scientifique a recueilli de nouvelles données",
        arabic: "بَيَانَات",
        example5: "جَمَعَ العَالِمُ بَيَانَاتٍ جَدِيدَةً",
        id: "1-9",
      },
      {
        english: "Unccustomed",
        example1: "She is unaccustomed to the cold weather.",
        chinese: "不习惯",
        example2: "她不习惯寒冷的天气",
        spanish: "No acostumbrado",
        example3: "Ella no está acostumbrada al clima frío",
        french: "Inhabituelle",
        example4: "Elle n’est pas habituée au temps froid",
        arabic: "غَيْرُ مُعْتَاد",
        example5: "هِيَ غَيْرُ مُعْتَادَةٍ عَلَى الطَّقْسِ البَارِدِ",
        id: "1-10",
      },
      {
        english: "Bachelor",
        example1: "He remained a bachelor all his life.",
        chinese: "学士",
        example2: "他一生都保持单身",
        spanish: "Bachiller",
        example3: "Él permaneció soltero toda su vida",
        french: "Célibataire",
        example4: "Il est resté célibataire toute sa vie",
        arabic: "أَعْزَب",
        example5: "بَقِيَ عَازِبًا طُولَ حَيَاتِهِ",
        id: "1-11",
      },
      {
        english: "Qualify",
        example1: "She qualified as a doctor last year.",
        chinese: "资格",
        example2: "她去年获得了医生资格",
        spanish: "Calificar",
        example3: "Ella se graduó como doctora el año pasado",
        french: "Qualifier",
        example4: "Elle est devenue médecin l’année dernière",
        arabic: "يَتَأَهَّل",
        example5: "تَخَرَّجَتْ كَطَبِيبَةٍ فِي السَّنَةِ المَاضِيَةِ",
        id: "1-12",
      },
    ],
  },
  {
    id: "2",
    title: "Lesson 2",
    words: [
      {
        english: "Corpse",
        example1:"The police found a corpse in the river",
        chinese: "尸体",
        example2:"警察在河里发现了一具尸体",
        spanish: "Cadáver",
        example3:"La policía encontró un cadáver en el río",
        french: "Cadavre",
        example4:"La police a trouvé un cadavre dans la rivière",
        arabic: "جُثّة",
        example5:"وَجَدَتِ الشُّرْطَةُ جُثَّةً فِي النَّهْرِ",
        id: "2-1",
      },
      {
        english: "Conceal",
        example1:"She concealed the letter in a drawer",
        chinese: "隐藏",
        example2:"她把信藏在抽屉里",
        spanish: "Ocultar",
        example3:"Ella escondió la carta en un cajón",
        french: "Cacher",
        example4:"Elle a caché la lettre dans un tiroir",
        arabic: "أَخْفى",
        example5:"أَخْفَتِ الرِّسَالَةَ فِي دُرْجٍ",
        id: "2-2",
      },
      {
        english: "Dismal",
        example1:"The weather was cold and dismal",
        chinese: "阴沉的",
        example2:"天气寒冷而阴沉",
        spanish: "Ocultar",
        example3:"El clima era frío y triste",
        french: "lugubre",
        example4:"Le temps était froid et sombre",
        arabic: "مُحْزِن",
        example5:"كَانَ الطَّقْسُ بَارِدًا وَكَئِيبًا",
        id: "2-3",
      },
      {
        english: "Frigid",
        example1:"The frigid wind made us shiver",
        chinese: "寒冷的",
        example2:"冰冷的风让我们发抖",
        spanish: "Frígido",
        example3:"El viento helado nos hizo temblar",
        french: "Glacial",
        example4:"Le vent glacial nous a fait frissonner",
        arabic: "بَارِد جِدًّا",
        example5:"جَعَلَنَا الرِّيحُ القَارِسُ نَرْتَعِشُ",
        id: "2-4",
      },
      {
        english: "Inhabit",
        example1:"Many birds inhabit this island",
        chinese: "居住",
        example2:"许多鸟类居住在这个岛上",
        spanish: "Habitar",
        example3:"Muchas aves habitan en esta isla",
        french: "Habiter",
        example4:"De nombreux oiseaux habitent cette île",
        arabic: "سَكَنَ",
        example5:"يَسْكُنُ الكَثِيرُ مِنَ الطُّيُورِ هَذِهِ الجَزِيرَةَ",
        id: "2-5",
      },
      {
        english: "Numb",
        example1:"His fingers were numb from the snow",
        chinese: "麻木的",
        example2:"他的手指因雪而麻木了",
        spanish: "Entumecido",
        example3:"Sus dedos estaban entumecidos por la nieve",
        french: "Engourdi",
        example4:"Ses doigts étaient engourdis par la neige",
        arabic: "خَدِر",
        example5:"كَانَتْ أَصَابِعُهُ مُتَجَمِّدَةً بِسَبَبِ الثَّلْجِ",
        id: "2-6",
      },
      {
        english: "Peril",
        example1:"The climbers faced great peril",
        chinese: "危险",
        example2:"登山者面临巨大的危险",
        spanish: "Peligro",
        example3:"Los escaladores enfrentaron un gran peligro",
        french: "Péril",
        example4:"Les alpinistes ont affronté un grand danger",
        arabic: "خَطَر جَسِيم",
        example5:"وَاجَهَ المُتَسَلِّقُونَ خَطَرًا عَظِيمًا",
        id: "2-7",
      },
      {
        english: "Recline",
        example1:"He reclined on the sofa to rest",
        chinese: "倚靠",
        example2:"他靠在沙发上休息",
        spanish: "Reclinarse",
        example3:"Él se recostó en el sofá para descansar",
        french: "S'allonger",
        example4:"Il s’est allongé sur le canapé pour se reposer",
        arabic: "اِتَّكَأَ",
        example5:"اِسْتَلْقَى عَلَى الأَرِيكَةِ لِيَسْتَرِيحَ",
        id: "2-8",
      },
      {
        english: "Shriek",
        example1:"She gave a loud shriek when she saw the mouse",
        chinese: "尖叫",
        example2:"她看到老鼠时大声尖叫",
        spanish: "Gritar",
        example3:"Ella dio un grito fuerte cuando vio el ratón",
        french: "Hurlement",
        example4:"Elle poussa un cri fort quand elle vit la souris",
        arabic: "صَرْخَة شَدِيدَة",
        example5:"أَطْلَقَتْ صَرْخَةً عَالِيَةً عِنْدَمَا رَأَتِ الفَأْرَ",
        id: "2-9",
      },
      {
        english: "Sinister",
        example1:"The house looked dark and sinister",
        chinese: "邪恶的",
        example2:"房子看起来阴暗而可怕",
        spanish: "Siniestro",
        example3:"La casa se veía oscura y siniestra",
        french: "Sinistre",
        example4:"La maison semblait sombre et sinistre",
        arabic: "مَشْؤُوم",
        example5:"بَدَا المَنْزِلُ مُظْلِمًا وَمُخِيفًا",
        id: "2-10",
      },
      {
        english: "Tempt",
        example1:"The cake tempted him to break his diet",
        chinese: "引诱",
        example2:"蛋糕诱使他打破了饮食计划",
        spanish: "Tentar",
        example3:"El pastel lo tentó a romper su dieta",
        french: "Tenter",
        example4:"Le gâteau l’a tenté de rompre son régime",
        arabic: "أَغْرَى",
        example5:"أَغْرَتْهُ الكَعْكَةُ بِكَسْرِ حِمْيَتِهِ",
        id: "2-11",
      },
      {
        english: "Wager",
        example1:"He made a wager on the football game",
        chinese: "打赌",
        example2:"他在足球比赛上打了个赌",
        spanish: "Apuesta",
        example3:"Él hizo una apuesta en el partido de fútbol",
        french: "Pari",
        example4:"Il a fait un pari sur le match de football",
        arabic: "رِهَان",
        example5:"رَاهَنَ عَلَى مُبَارَاةِ كُرَةِ القَدَمِ",
        id: "2-12",
      },
    ],
  },
  {
    id: "3",
    title: "Lesson 3",
    words: [
      {
        english: "Typical",
        chinese: "典型的",
        spanish: "Típico",
        french: "Typique",
        arabic: "نَمُوذَجِيّ",
        id: "3-1",
      },
      {
        english: "Minimum",
        chinese: "最小的",
        spanish: "Mínimo",
        french: "Minimum",
        arabic: "الحَدُّ الأَدْنَى",
        id: "3-2",
      },
      {
        english: "Scarce",
        chinese: "稀少的",
        spanish: "Escaso",
        french: "Rare",
        arabic: "نَادِر",
        id: "3-3",
      },
      {
        english: "Annual",
        chinese: "每年的",
        spanish: "Anual",
        french: "Annuel",
        arabic: "سَنَوِيّ",
        id: "3-4",
      },
      {
        english: "Persuade",
        chinese: "说服",
        spanish: "Persuadir",
        french: "Persuader",
        arabic: "أَقْنَعَ",
        id: "3-5",
      },
      {
        english: "Essential",
        chinese: "必要的",
        spanish: "Esencial",
        french: "Essentiel",
        arabic: "ضَرُورِيّ",
        id: "3-6",
      },
      {
        english: "Blend",
        chinese: "混合",
        spanish: "Mezclar",
        french: "Mélanger",
        arabic: "خَلَطَ",
        id: "3-7",
      },
      {
        english: "Visible",
        chinese: "可见的",
        spanish: "Visible",
        french: "Visible",
        arabic: "مَرْئِيّ",
        id: "3-8",
      },
      {
        english: "Expensive",
        chinese: "昂贵的",
        spanish: "Caro",
        french: "Cher",
        arabic: "غَالٍ",
        id: "3-9",
      },
      {
        english: "Talent",
        chinese: "才能",
        spanish: "Talento",
        french: "Talent",
        arabic: "مَوْهِبَة",
        id: "3-10",
      },
      {
        english: "Devise",
        chinese: "发明",
        spanish: "Idear",
        french: "Concevoir",
        arabic: "صَمَّمَ",
        id: "3-11",
      },
      {
        english: "Wholesale",
        chinese: "批发的",
        spanish: "Al por mayor",
        french: "En gros",
        arabic: "بَيْعٌ جُمْلَةً",
        id: "3-12",
      },
    ],
  },
  {
    id: "4",
    title: "Lesson 4",
    words: [
      {
        english: "Vapor",
        chinese: "蒸汽",
        spanish: "Vapor",
        french: "Vapeur",
        arabic: "بُخَار",
        id: "4-1",
      },
      {
        english: "Eliminate",
        chinese: "消除",
        spanish: "Eliminar",
        french: "Eliminer",
        arabic: "أَزَالَ",
        id: "4-2",
      },
      {
        english: "Villain",
        chinese: "恶棍",
        spanish: "Villano",
        french: "Vilain",
        arabic: "شِرِّير",
        id: "4-3",
      },
      {
        english: "Dense",
        chinese: "稠密的",
        spanish: "Denso",
        french: "Dense",
        arabic: "كَثِيف",
        id: "4-4",
      },
      {
        english: "Utilize",
        chinese: "利用",
        spanish: "Utilizar",
        french: "Utiliser",
        arabic: "اسْتَخْدَمَ",
        id: "4-5",
      },
      {
        english: "Humid",
        chinese: "潮湿的",
        spanish: "Húmedo",
        french: "Humide",
        arabic: "رَطْب",
        id: "4-6",
      },
      {
        english: "Theory",
        chinese: "理论",
        spanish: "Teoría",
        french: "Théorie",
        arabic: "نَظَرِيَّة",
        id: "4-7",
      },
      {
        english: "Descend",
        chinese: "下降",
        spanish: "Descender",
        french: "Descendre",
        arabic: "نَزَلَ",
        id: "4-8",
      },
      {
        english: "Circulate",
        chinese: "循环",
        spanish: "Circular",
        french: "Circuler",
        arabic: "دَارَ",
        id: "4-9",
      },
      {
        english: "Enormous",
        chinese: "巨大的",
        spanish: "Enorme",
        french: "Enorme",
        arabic: "ضَخْم",
        id: "4-10",
      },
      {
        english: "Predict",
        chinese: "预测",
        spanish: "Predecir",
        french: "Prédire",
        arabic: "تَنَبَّأَ",
        id: "4-11",
      },
      {
        english: "Vanish",
        chinese: "消失",
        spanish: "Desaparecer",
        french: "Disparaître",
        arabic: "تَلاشَى",
        id: "4-12",
      },
    ],
  },
  {
    id: "5",
    title: "Lesson 5",
    words: [
      {
        english: "Tradition",
        chinese: "传统",
        spanish: "Tradición",
        french: "Tradition",
        arabic: "تَقْلِيد",
        id: "5-1",
      },
      {
        english: "Rural",
        chinese: "农村的",
        spanish: "Rural",
        french: "Rural",
        arabic: "رِيفِيّ",
        id: "5-2",
      },
      {
        english: "Burden",
        chinese: "负担",
        spanish: "Carga",
        french: "Fardeau",
        arabic: "عِبْء",
        id: "5-3",
      },
      {
        english: "Campus",
        chinese: "校园",
        spanish: "Campus universitario",
        french: "Campus",
        arabic: "حَرَم جامِعِيّ",
        id: "5-4",
      },
      {
        english: "Majority",
        chinese: "多数",
        spanish: "Mayoría",
        french: "Majorité",
        arabic: "أَكْثَرِيَّة",
        id: "5-5",
      },
      {
        english: "Assemble",
        chinese: "集合",
        spanish: "Ensamblar",
        french: "Assembler",
        arabic: "اجْتَمَعَ",
        id: "5-6",
      },
      {
        english: "Explore",
        chinese: "探索",
        spanish: "Explorar",
        french: "Explorer",
        arabic: "اسْتَكْشَفَ",
        id: "5-7",
      },
      {
        english: "Topic",
        chinese: "话题",
        spanish: "Tema",
        french: "Sujet",
        arabic: "مَوْضُوع",
        id: "5-8",
      },
      {
        english: "Debate",
        chinese: "辩论",
        spanish: "Debate",
        french: "Débat",
        arabic: "مُنَاقَشَة",
        id: "5-9",
      },
      {
        english: "Evade",
        chinese: "逃避",
        spanish: "Evadir",
        french: "Eviter",
        arabic: "تَجَنَّبَ",
        id: "5-10",
      },
      {
        english: "Probe",
        chinese: "探查",
        spanish: "Investigar",
        french: "Sonder",
        arabic: "فَحَصَ",
        id: "5-11",
      },
      {
        english: "Reform",
        chinese: "改革",
        spanish: "Reforma",
        french: "Réforme",
        arabic: "إِصْلَاح",
        id: "5-12",
      },
    ],
  },
      {
    id: "6",
    title: "Lesson 6",
    words: [
      {
        english: "Approach",
        chinese: "接近",
        spanish: "Acercarse",
        french: "Approche",
        arabic: "اِقْتَرَبَ",
        id: "6-1",
      },
      {
        english: "Detect",
        chinese: "发现",
        spanish: "Detectar",
        french: "Détecter",
        arabic: "كَشَفَ",
        id: "6-2",
      },
      {
        english: "Defect",
        chinese: "缺陷",
        spanish: "Defecto",
        french: "Défaut",
        arabic: "عَيْب",
        id: "6-3",
      },
      {
        english: "Employee",
        chinese: "雇员",
        spanish: "Empleado",
        french: "Employé",
        arabic: "مُوَظَّف",
        id: "6-4",
      },
      {
        english: "Neglect",
        chinese: "忽视",
        spanish: "Descuidar",
        french: "Négliger",
        arabic: "أَهْمَلَ",
        id: "6-5",
      },
      {
        english: "Deceive",
        chinese: "欺骗",
        spanish: "Engañar",
        french: "Tromper",
        arabic: "خَدَعَ",
        id: "6-6",
      },
      {
        english: "Undoubtedly",
        chinese: "毫无疑问地",
        spanish: "Indudablemente",
        french: "Sans aucun doute",
        arabic: "بِدُونِ شَكّ",
        id: "6-7",
      },
      {
        english: "Popular",
        chinese: "受欢迎的",
        spanish: "Popular",
        french: "Populaire",
        arabic: "شَعْبِيّ",
        id: "6-8",
      },
      {
        english: "Thorough",
        chinese: "彻底的",
        spanish: "Minucioso",
        french: "Minutieux",
        arabic: "شَامِل",
        id: "6-9",
      },
      {
        english: "Client",
        chinese: "客户",
        spanish: "Cliente",
        french: "Client",
        arabic: "عَمِيل",
        id: "6-10",
      },
      {
        english: "Comprehensive",
        chinese: "全面的",
        spanish: "Comprensivo",
        french: "Complet",
        arabic: "شَامِل",
        id: "6-11",
      },
      {
        english: "Defraud",
        chinese: "欺诈",
        spanish: "Defraudar",
        french: "Escroquer",
        arabic: "اِحْتَالَ",
        id: "6-12",
      },
    ],
  },
  {
    id: "7",
    title: "Lesson 7",
    words: [
      {
        english: "Postpone",
        chinese: "推迟",
        spanish: "Posponer",
        french: "Reporter",
        arabic: "أَجَّلَ",
        id: "7-1",
      },
      {
        english: "Consent",
        chinese: "同意",
        spanish: "Consentir",
        french: "Consentir",
        arabic: "مُوَافَقَة",
        id: "7-2",
      },
      {
        english: "Massive",
        chinese: "巨大的",
        spanish: "Masivo",
        french: "Massif",
        arabic: "ضَخْم",
        id: "7-3",
      },
      {
        english: "Capsule",
        chinese: "胶囊",
        spanish: "Cápsula",
        french: "Capsule",
        arabic: "كَبْسُولَة",
        id: "7-4",
      },
      {
        english: "Preserve",
        chinese: "保存",
        spanish: "Preservar",
        french: "Préserver",
        arabic: "حَفِظَ",
        id: "7-5",
      },
      {
        english: "Denounce",
        chinese: "谴责",
        spanish: "Denunciar",
        french: "Dénoncer",
        arabic: "شَجَبَ",
        id: "7-6",
      },
      {
        english: "Unique",
        chinese: "独特的",
        spanish: "Unico",
        french: "Unique",
        arabic: "فَرِيد",
        id: "7-7",
      },
      {
        english: "Torrent",
        chinese: "急流",
        spanish: "Torrente",
        french: "Torrent",
        arabic: "سَيْل جَارِف",
        id: "7-8",
      },
      {
        english: "Resent",
        chinese: "怨恨",
        spanish: "Resentir",
        french: "En vouloir à",
        arabic: "سَخِطَ",
        id: "7-9",
      },
      {
        english: "Molest",
        chinese: "骚扰",
        spanish: "Molestar",
        french: "Importuner",
        arabic: "تَحَرَّشَ",
        id: "7-10",
      },
      {
        english: "Gloomy",
        chinese: "阴郁的",
        spanish: "Sombrío",
        french: "Sombre",
        arabic: "كَئِيب",
        id: "7-11",
      },
      {
        english: "Unforeseen",
        chinese: "出乎意料的",
        spanish: "Imprevisto",
        french: "Imprévu",
        arabic: "غَيْر مُتَوَقَّع",
        id: "7-12",
      },
    ],
  },
];





