export const lessons = [
  {
    id: "1",
    title: "Lesson 1",
    words: [
      {
        english: "Abandon",
        example1: "He abandoned the old house",
        chinese: "放弃",
        example2: "他抛弃了那座老房子",
        spanish: "Abandonar",
        example3: "Él abandonó la casa vieja",
        french: "Abandonner",
        example4: "Il a abandonné la vieille maison",
        arabic: "تَرَكَ",
        example5: "تَرَكَ الْمَنْزِلَ الْقَدِيمَ",
        id: "1-1",
      },
      {
        english: "Keen",
        example1: "She is keen to learn new skills",
        chinese: "敏锐的",
        example2: "她很渴望学习新技能",
        spanish: "Interesada",
        example3: "Ella está deseosa de aprender nuevas habilidades",
        french: "Passionnée",
        example4: "Elle est désireuse d’apprendre de nouvelles compétences",
        arabic: "حَادّ",
        example5: "هي مُتَحَمِّسَةٌ لِتَعَلُّمِ مَهَارَاتٍ جَدِيدَةٍ",
        id: "1-2",
      },
      {
        english: "Jealous",
        example1: "He felt jealous of his brother’s success.",
        chinese: "嫉妒的",
        example2: "他对他哥哥的成功感到嫉妒",
        spanish: "Celosa",
        example3: "Él sintió envidia del éxito de su hermano",
        french: "Jalouse",
        example4: "Il a ressenti de la jalousie face au succès de son frère",
        arabic: "غَيُور",
        example5: "شَعَرَ بِالغِيرَةِ مِن نَجَاحِ أَخِيهِ",
        id: "1-3",
      },
      {
        english: "Tact",
        example1: "She handled the problem with tact.",
        chinese: "机智",
        example2: "她机智地处理了这个问题",
        spanish: "Tacto",
        example3: "Ella manejó el problema con tacto",
        french: "Tact",
        example4: "Elle a géré le problème avec tact",
        arabic: "لَبَاقَة",
        example5: "تَعَامَلَتْ مَعَ المُشْكِلَةِ بِدِقَّةٍ وَحِكْمَةٍ",
        id: "1-4",
      },
      {
        english: "Oath",
        example1: "He took an oath to tell the truth.",
        chinese: "誓言",
        example2: "他宣誓要说实话",
        spanish: "Juramento",
        example3: "Él juró decir la verdad",
        french: "Serment",
        example4: "Il a prêté serment de dire la vérité",
        arabic: "قَسَم",
        example5: "أَدَّى قَسَمًا لِيَقُولَ الحَقَّ",
        id: "1-5",
      },
      {
        english: "Vacant",
        example1: "The seat next to her was vacant.",
        chinese: "空缺",
        example2: "她旁边的座位是空的",
        spanish: "Vacante",
        example3: "El asiento a su lado estaba vacío",
        french: "Vacante",
        example4: "Le siège à côté d’elle était vide",
        arabic: "شَاغِر",
        example5: "كَانَ المَقْعَدُ بِجَانِبِهَا فَارِغًا",
        id: "1-6",
      },
      {
        english: "Hardship",
        example1: "They suffered hardship during the war.",
        chinese: "困难",
        example2: "他们在战争中遭受了苦难",
        spanish: "Privación",
        example3: "Ellos sufrieron dificultades durante la guerra",
        french: "Épreuves",
        example4: "Ils ont souffert de difficultés pendant la guerre",
        arabic: "مَشَقَّة",
        example5: "عَانَوْا مِنَ المَشَقَّةِ خِلَالَ الحَرْبِ",
        id: "1-7",
      },
      {
        english: "Gallant",
        example1: "The gallant soldier saved his friend.",
        chinese: "英勇",
        example2: "那个英勇的士兵救了他的朋友",
        spanish: "Galante",
        example3: "El soldado valiente salvó a su amigo",
        french: "Galante",
        example4: "Le soldat vaillant a sauvé son ami",
        arabic: "شُجَاع",
        example5: "أَنْقَذَ الجُنْدِيُّ الشُّجَاعُ صَدِيقَهُ",
        id: "1-8",
      },
      {
        english: "Data",
        example1: "The scientist collected new data.",
        chinese: "数据",
        example2: "科学家收集了新的数据",
        spanish: "Datos",
        example3: "El científico recopiló nuevos datos",
        french: "Données",
        example4: "Le scientifique a recueilli de nouvelles données",
        arabic: "بَيَانَات",
        example5: "جَمَعَ العَالِمُ بَيَانَاتٍ جَدِيدَةً",
        id: "1-9",
      },
      {
        english: "Unccustomed",
        example1: "She is unaccustomed to the cold weather.",
        chinese: "不习惯",
        example2: "她不习惯寒冷的天气",
        spanish: "No acostumbrado",
        example3: "Ella no está acostumbrada al clima frío",
        french: "Inhabituelle",
        example4: "Elle n’est pas habituée au temps froid",
        arabic: "غَيْرُ مُعْتَاد",
        example5: "هِيَ غَيْرُ مُعْتَادَةٍ عَلَى الطَّقْسِ البَارِدِ",
        id: "1-10",
      },
      {
        english: "Bachelor",
        example1: "He remained a bachelor all his life.",
        chinese: "学士",
        example2: "他一生都保持单身",
        spanish: "Bachiller",
        example3: "Él permaneció soltero toda su vida",
        french: "Célibataire",
        example4: "Il est resté célibataire toute sa vie",
        arabic: "أَعْزَب",
        example5: "بَقِيَ عَازِبًا طُولَ حَيَاتِهِ",
        id: "1-11",
      },
      {
        english: "Qualify",
        example1: "She qualified as a doctor last year.",
        chinese: "资格",
        example2: "她去年获得了医生资格",
        spanish: "Calificar",
        example3: "Ella se graduó como doctora el año pasado",
        french: "Qualifier",
        example4: "Elle est devenue médecin l’année dernière",
        arabic: "يَتَأَهَّل",
        example5: "تَخَرَّجَتْ كَطَبِيبَةٍ فِي السَّنَةِ المَاضِيَةِ",
        id: "1-12",
      },
    ],
  },
  {
    id: "2",
    title: "Lesson 2",
    words: [
      {
        english: "Corpse",
        example1:"The police found a corpse in the river",
        chinese: "尸体",
        example2:"警察在河里发现了一具尸体",
        spanish: "Cadáver",
        example3:"La policía encontró un cadáver en el río",
        french: "Cadavre",
        example4:"La police a trouvé un cadavre dans la rivière",
        arabic: "جُثّة",
        example5:"وَجَدَتِ الشُّرْطَةُ جُثَّةً فِي النَّهْرِ",
        id: "2-1",
      },
      {
        english: "Conceal",
        example1:"She concealed the letter in a drawer",
        chinese: "隐藏",
        example2:"她把信藏在抽屉里",
        spanish: "Ocultar",
        example3:"Ella escondió la carta en un cajón",
        french: "Cacher",
        example4:"Elle a caché la lettre dans un tiroir",
        arabic: "أَخْفى",
        example5:"أَخْفَتِ الرِّسَالَةَ فِي دُرْجٍ",
        id: "2-2",
      },
      {
        english: "Dismal",
        example1:"The weather was cold and dismal",
        chinese: "阴沉的",
        example2:"天气寒冷而阴沉",
        spanish: "Ocultar",
        example3:"El clima era frío y triste",
        french: "lugubre",
        example4:"Le temps était froid et sombre",
        arabic: "مُحْزِن",
        example5:"كَانَ الطَّقْسُ بَارِدًا وَكَئِيبًا",
        id: "2-3",
      },
      {
        english: "Frigid",
        example1:"The frigid wind made us shiver",
        chinese: "寒冷的",
        example2:"冰冷的风让我们发抖",
        spanish: "Frígido",
        example3:"El viento helado nos hizo temblar",
        french: "Glacial",
        example4:"Le vent glacial nous a fait frissonner",
        arabic: "بَارِد جِدًّا",
        example5:"جَعَلَنَا الرِّيحُ القَارِسُ نَرْتَعِشُ",
        id: "2-4",
      },
      {
        english: "Inhabit",
        example1:"Many birds inhabit this island",
        chinese: "居住",
        example2:"许多鸟类居住在这个岛上",
        spanish: "Habitar",
        example3:"Muchas aves habitan en esta isla",
        french: "Habiter",
        example4:"De nombreux oiseaux habitent cette île",
        arabic: "سَكَنَ",
        example5:"يَسْكُنُ الكَثِيرُ مِنَ الطُّيُورِ هَذِهِ الجَزِيرَةَ",
        id: "2-5",
      },
      {
        english: "Numb",
        example1:"His fingers were numb from the snow",
        chinese: "麻木的",
        example2:"他的手指因雪而麻木了",
        spanish: "Entumecido",
        example3:"Sus dedos estaban entumecidos por la nieve",
        french: "Engourdi",
        example4:"Ses doigts étaient engourdis par la neige",
        arabic: "خَدِر",
        example5:"كَانَتْ أَصَابِعُهُ مُتَجَمِّدَةً بِسَبَبِ الثَّلْجِ",
        id: "2-6",
      },
      {
        english: "Peril",
        example1:"The climbers faced great peril",
        chinese: "危险",
        example2:"登山者面临巨大的危险",
        spanish: "Peligro",
        example3:"Los escaladores enfrentaron un gran peligro",
        french: "Péril",
        example4:"Les alpinistes ont affronté un grand danger",
        arabic: "خَطَر جَسِيم",
        example5:"وَاجَهَ المُتَسَلِّقُونَ خَطَرًا عَظِيمًا",
        id: "2-7",
      },
      {
        english: "Recline",
        example1:"He reclined on the sofa to rest",
        chinese: "倚靠",
        example2:"他靠在沙发上休息",
        spanish: "Reclinarse",
        example3:"Él se recostó en el sofá para descansar",
        french: "S'allonger",
        example4:"Il s’est allongé sur le canapé pour se reposer",
        arabic: "اِتَّكَأَ",
        example5:"اِسْتَلْقَى عَلَى الأَرِيكَةِ لِيَسْتَرِيحَ",
        id: "2-8",
      },
      {
        english: "Shriek",
        example1:"She gave a loud shriek when she saw the mouse",
        chinese: "尖叫",
        example2:"她看到老鼠时大声尖叫",
        spanish: "Gritar",
        example3:"Ella dio un grito fuerte cuando vio el ratón",
        french: "Hurlement",
        example4:"Elle poussa un cri fort quand elle vit la souris",
        arabic: "صَرْخَة شَدِيدَة",
        example5:"أَطْلَقَتْ صَرْخَةً عَالِيَةً عِنْدَمَا رَأَتِ الفَأْرَ",
        id: "2-9",
      },
      {
        english: "Sinister",
        example1:"The house looked dark and sinister",
        chinese: "邪恶的",
        example2:"房子看起来阴暗而可怕",
        spanish: "Siniestro",
        example3:"La casa se veía oscura y siniestra",
        french: "Sinistre",
        example4:"La maison semblait sombre et sinistre",
        arabic: "مَشْؤُوم",
        example5:"بَدَا المَنْزِلُ مُظْلِمًا وَمُخِيفًا",
        id: "2-10",
      },
      {
        english: "Tempt",
        example1:"The cake tempted him to break his diet",
        chinese: "引诱",
        example2:"蛋糕诱使他打破了饮食计划",
        spanish: "Tentar",
        example3:"El pastel lo tentó a romper su dieta",
        french: "Tenter",
        example4:"Le gâteau l’a tenté de rompre son régime",
        arabic: "أَغْرَى",
        example5:"أَغْرَتْهُ الكَعْكَةُ بِكَسْرِ حِمْيَتِهِ",
        id: "2-11",
      },
      {
        english: "Wager",
        example1:"He made a wager on the football game",
        chinese: "打赌",
        example2:"他在足球比赛上打了个赌",
        spanish: "Apuesta",
        example3:"Él hizo una apuesta en el partido de fútbol",
        french: "Pari",
        example4:"Il a fait un pari sur le match de football",
        arabic: "رِهَان",
        example5:"رَاهَنَ عَلَى مُبَارَاةِ كُرَةِ القَدَمِ",
        id: "2-12",
      },
    ],
  },
  {
    id: "3",
    title: "Lesson 3",
    words: [
      {
        english: "Typical",
        example1:"This is a typical Italian dish",
        chinese: "典型的",
        example2:"这是一道典型的意大利菜",
        spanish: "Típico",
        example3:"Este es un plato típico italiano",
        french: "Typique",
        example4:"C’est un plat italien typique",
        arabic: "نَمُوذَجِيّ",
        example5:"هَذَا طَبَقٌ إِيطَالِيٌّ نَمُوذَجِيٌّ",
        id: "3-1",
      },
      {
        english: "Minimum",
        example1:"The minimum age to vote is eighteen",
        chinese: "最小的",
        example2:"投票的最低年龄是十八岁",
        spanish: "Mínimo",
        example3:"La edad mínima para votar es dieciocho",
        french: "Minimum",
        example4:"L’âge minimum pour voter est dix-huit ans",
        arabic: "الحَدُّ الأَدْنَى",
        example5:"أَدْنَى سِنٍّ لِلتَّصْوِيتِ هُوَ ثَمَانِيَةَ عَشَرَ عَامًا",
        id: "3-2",
      },
      {
        english: "Scarce",
        example1:"Water is scarce in the desert",
        chinese: "稀少的",
        example2:"沙漠里水很稀缺",
        spanish: "Escaso",
        example3:"El agua es escasa en el desierto",
        french: "Rare",
        example4:"L’eau est rare dans le désert",
        arabic: "نَادِر",
        example5:"المَاءُ نَادِرٌ فِي الصَّحْرَاءِ",
        id: "3-3",
      },
      {
        english: "Annual",
        example1:"We have an annual family gathering",
        chinese: "每年的",
        example2:"我们有一次年度家庭聚会",
        spanish: "Anual",
        example3:"Tenemos una reunión familiar anual",
        french: "Annuel",
        example4:"Nous avons une réunion de famille annuelle",
        arabic: "سَنَوِيّ",
        example5:"لَدَيْنَا اجْتِمَاعٌ عَائِلِيٌّ سَنَوِيٌّ",
        id: "3-4",
      },
      {
        english: "Persuade",
        example1:"He persuaded me to join the club",
        chinese: "说服",
        example2:"他说服我加入俱乐部",
        spanish: "Persuadir",
        example3:"Él me persuadió para unirme al club",
        french: "Persuader",
        example4:"Il m’a persuadé de rejoindre le club",
        arabic: "أَقْنَعَ",
        example5:"أَقْنَعَنِي بِالانْضِمَامِ إِلَى النَّادِي",
        id: "3-5",
      },
      {
        english: "Essential",
        example1:"Food and water are essential for life",
        chinese: "必要的",
        example2:"食物和水是生命必需的",
        spanish: "Esencial",
        example3:"La comida y el agua son esenciales para la vida",
        french: "Essentiel",
        example4:"La nourriture et l’eau sont essentielles à la vie",
        arabic: "ضَرُورِيّ",
        example5:"الطَّعَامُ وَالمَاءُ ضَرُورِيَّانِ لِلْحَيَاةِ",
        id: "3-6",
      },
      {
        english: "Blend",
        example1:"She blended milk and fruit to make a smoothie",
        chinese: "混合",
        example2:"她把牛奶和水果混合做成奶昔",
        spanish: "Mezclar",
        example3:"Ella mezcló leche y fruta para hacer un batido",
        french: "Mélanger",
        example4:"Elle a mélangé du lait et des fruits pour faire un smoothie",
        arabic: "خَلَطَ",
        example5:"مَزَجَتِ الحَلِيبَ وَالفَاكِهَةَ لِتَصْنَعَ عَصِيرًا",
        id: "3-7",
      },
      {
        english: "Visible",
        example1:"The stars are visible tonight",
        chinese: "可见的",
        example2:"今晚星星是可见的",
        spanish: "Visible",
        example3:"Las estrellas son visibles esta noche",
        french: "Visible",
        example4:"Les étoiles sont visibles ce soir",
        arabic: "مَرْئِيّ",
        example5:"النُّجُومُ مَرْئِيَّةٌ اللَّيْلَةَ",
        id: "3-8",
      },
      {
        english: "Expensive",
        example1:"This car is too expensive for me",
        chinese: "昂贵的",
        example2:"这辆车对我来说太贵了",
        spanish: "Caro",
        example3:"Este coche es demasiado caro para mí",
        french: "Cher",
        example4:"Cette voiture est trop chère pour moi",
        arabic: "غَالٍ",
        example5:"هَذِهِ السَّيَّارَةُ غَالِيَةٌ جِدًّا عَلَيَّ",
        id: "3-9",
      },
      {
        english: "Talent",
        example1:"She has a talent for painting",
        chinese: "才能",
        example2:"她有绘画的天赋",
        spanish: "Talento",
        example3:"Ella tiene talento para la pintura",
        french: "Talent",
        example4:"Elle a du talent pour la peinture",
        arabic: "مَوْهِبَة",
        example5:"لَدَيْهَا مَوْهِبَةٌ فِي الرَّسْمِ",
        id: "3-10",
      },
      {
        english: "Devise",
        example1:"They devised a new method of teaching",
        chinese: "发明",
        example2:"他们设计了一种新的教学方法",
        spanish: "Idear",
        example3:"Ellos idearon un nuevo método de enseñanza",
        french: "Concevoir",
        example4:"Ils ont conçu une nouvelle méthode d’enseignement",
        arabic: "صَمَّمَ",
        example5:"وَضَعُوا طَرِيقَةً جَدِيدَةً لِلتَّدْرِيسِ",
        id: "3-11",
      },
      {
        english: "Wholesale",
        example1:"The store sells clothes at wholesale prices",
        chinese: "批发的",
        example2:"这家商店批发价出售衣服",
        spanish: "Al por mayor",
        example3:"La tienda vende ropa a precios de mayoreo",
        french: "En gros",
        example4:"Le magasin vend des vêtements à des prix de gros",
        arabic: "بَيْعٌ جُمْلَةً",
        example5:"يَبِيعُ المَتْجَرُ المَلابِسَ بِأَسْعَارِ الجُمْلَةِ",
        id: "3-12",
      },
    ],
  },
  {
    id: "4",
    title: "Lesson 4",
    words: [
      {
        english: "Vapor",
        example1:"Hot water changes into vapor",
        chinese: "蒸汽",
        example2:"热水变成蒸汽",
        spanish: "Vapor",
        example3:"El agua caliente se convierte en vapor",
        french: "Vapeur",
        example4:"L’eau chaude se transforme en vapeur",
        arabic: "بُخَار",
        example5:"يَتَحَوَّلُ المَاءُ السَّاخِنُ إِلَى بُخَارٍ",
        id: "4-1",
      },
      {
        english: "Eliminate",
        example1:"The team eliminated their weak player",
        chinese: "消除",
        example2:"球队淘汰了他们的弱队员",
        spanish: "Eliminar",
        example3:"El equipo eliminó a su jugador débil",
        french: "Eliminer",
        example4:"L’équipe a éliminé son joueur faible",
        arabic: "أَزَالَ",
        example5:"أَزَالَ الفَرِيقُ لَاعِبَهُم الضَّعِيفَ",
        id: "4-2",
      },
      {
        english: "Villain",
        example1:"The villain in the movie was caught",
        chinese: "恶棍",
        example2:"电影里的坏人被抓住了",
        spanish: "Villano",
        example3:"El villano de la película fue atrapado",
        french: "Vilain",
        example4:"Le méchant du film a été attrapé",
        arabic: "شِرِّير",
        example5:"قُبِضَ عَلَى الشِّرِّيرِ فِي الفِلْمِ",
        id: "4-3",
      },
      {
        english: "Dense",
        example1:"The forest was dense with trees",
        chinese: "稠密的",
        example2:"森林里树木茂密",
        spanish: "Denso",
        example3:"El bosque estaba denso de árboles",
        french: "Dense",
        example4:"La forêt était dense avec des arbres",
        arabic: "كَثِيف",
        example5:"كَانَتِ الغَابَةُ كَثِيفَةَ الأَشْجَارِ",
        id: "4-4",
      },
      {
        english: "Utilize",
        example1:"She utilized her free time to study",
        chinese: "利用",
        example2:"她利用空闲时间学习",
        spanish: "Utilizar",
        example3:"Ella utilizó su tiempo libre para estudiar",
        french: "Utiliser",
        example4:"Elle a utilisé son temps libre pour étudier",
        arabic: "اسْتَخْدَمَ",
        example5:"اِسْتَغَلَّتْ وَقْتَهَا الفَارِغَ فِي الدِّرَاسَةِ",
        id: "4-5",
      },
      {
        english: "Humid",
        example1:"The weather was hot and humid",
        chinese: "潮湿的",
        example2:"天气炎热又潮湿",
        spanish: "Húmedo",
        example3:"El clima estaba caluroso y húmedo",
        french: "Humide",
        example4:"Le temps était chaud et humide",
        arabic: "رَطْب",
        example5:"كَانَ الطَّقْسُ حَارًّا وَرَطْبًا",
        id: "4-6",
      },
      {
        english: "Theory",
        example1:"He explained his theory in class",
        chinese: "理论",
        example2:"他在课堂上解释了他的理论",
        spanish: "Teoría",
        example3:"Él explicó su teoría en clase",
        french: "Théorie",
        example4:"Il a expliqué sa théorie en classe",
        arabic: "نَظَرِيَّة",
        example5:"شَرَحَ نَظَرِيَّتَهُ فِي الصَّفِّ",
        id: "4-7",
      },
      {
        english: "Descend",
        example1:"The plane began to descend",
        chinese: "下降",
        example2:"飞机开始下降",
        spanish: "Descender",
        example3:"El avión comenzó a descender",
        french: "Descendre",
        example4:"L’avion a commencé à descendre",
        arabic: "نَزَلَ",
        example5:"بَدَأَتِ الطَّائِرَةُ بِالنُّزُولِ",
        id: "4-8",
      },
      {
        english: "Circulate",
        example1:"Blood circulates in the body",
        chinese: "循环",
        example2:"血液在身体里循环",
        spanish: "Circular",
        example3:"La sangre circula en el cuerpo",
        french: "Circuler",
        example4:"Le sang circule dans le corps",
        arabic: "دَارَ",
        example5:"يَدُورُ الدَّمُ فِي الجِسْمِ",
        id: "4-9",
      },
      {
        english: "Enormous",
        example1:"They live in an enormous house",
        chinese: "巨大的",
        example2:"他们住在一栋巨大的房子里",
        spanish: "Enorme",
        example3:"Ellos viven en una casa enorme",
        french: "Enorme",
        example4:"Ils vivent dans une maison énorme",
        arabic: "ضَخْم",
        example5:"يَسْكُنُونَ فِي مَنْزِلٍ ضَخْمٍ",
        id: "4-10",
      },
      {
        english: "Predict",
        example1:"Scientists predict heavy rain tomorrow",
        chinese: "预测",
        example2:"科学家预测明天有大雨",
        spanish: "Predecir",
        example3:"Los científicos predicen fuertes lluvias para mañana",
        french: "Prédire",
        example4:"Les scientifiques prédisent de fortes pluies demain",
        arabic: "تَنَبَّأَ",
        example5:"تَوَقَّعُ العُلَمَاءُ هُطُولَ أَمْطَارٍ غَزِيرَةٍ غَدًا",
        id: "4-11",
      },
      {
        english: "Vanish",
        example1:"The magician made the rabbit vanish",
        chinese: "消失",
        example2:"魔术师让兔子消失了",
        spanish: "Desaparecer",
        example3:"El mago hizo desaparecer al conejo",
        french: "Disparaître",
        example4:"Le magicien a fait disparaître le lapin",
        arabic: "تَلاشَى",
        example5:"جَعَلَ السَّاحِرُ الأَرْنَبَ يَخْتَفِي",
        id: "4-12",
      },
    ],
  },
  {
    id: "5",
    title: "Lesson 5",
    words: [
      {
        english: "Tradition",
        example1:"It is their tradition to celebrate together?",
        chinese: "传统",
        example2:"他们的传统是一起庆祝",
        spanish: "Tradición",
        example3:"Es su tradición celebrar juntos",
        french: "Tradition",
        example4:"C’est leur tradition de fêter ensemble",
        arabic: "تَقْلِيد",
        example5:"مِنْ تَقَالِيدِهِم أَنْ يَحْتَفِلُوا مَعًا",
        id: "5-1",
      },
      {
        english: "Rural",
        example1:"She prefers living in a rural area",
        chinese: "农村的",
        example2:"她更喜欢住在农村地区",
        spanish: "Rural",
        example3:"Ella prefiere vivir en una zona rural",
        french: "Rural",
        example4:"Elle préfère vivre dans une région rurale",
        arabic: "رِيفِيّ",
        example5:"تُفَضِّلُ العَيْشَ فِي مَنْطِقَةٍ رِيفِيَّةٍ",
        id: "5-2",
      },
      {
        english: "Burden",
        example1:"Paying the rent was a burden for him",
        chinese: "负担",
        example2:"付房租对他来说是个负担",
        spanish: "Carga",
        example3:"Pagar el alquiler fue una carga para él",
        french: "Fardeau",
        example4:"Payer le loyer était un fardeau pour lui",
        arabic: "عِبْء",
        example5:"كَانَ دَفْعُ الإِيجَارِ عِبْئًا عَلَيْهِ",
        id: "5-3",
      },
      {
        english: "Campus",
        example1:"The students walked across the campus",
        chinese: "校园",
        example2:"学生们走过校园",
        spanish: "Campus universitario",
        example3:"Los estudiantes caminaron por el campus",
        french: "Campus",
        example4:"Les étudiants ont traversé le campus",
        arabic: "حَرَم جامِعِيّ",
        example5:"مَشَى الطُّلَّابُ فِي أَرْجَاءِ الحَرَمِ الجَامِعِيِّ",
        id: "5-4",
      },
      {
        english: "Majority",
        example1:"The majority of people voted for him",
        chinese: "多数",
        example2:"大多数人投票给了他",
        spanish: "Mayoría",
        example3:"La mayoría de la gente votó por él",
        french: "Majorité",
        example4:"La majorité des gens a voté pour lui",
        arabic: "أَكْثَرِيَّة",
        example5:"صَوَّتَتِ الأَغْلَبِيَّةُ لَهُ",
        id: "5-5",
      },
      {
        english: "Assemble",
        example1:"The workers assembled in the hall",
        chinese: "集合",
        example2:"工人们在大厅里集合",
        spanish: "Ensamblar",
        example3:"Los trabajadores se reunieron en el salón",
        french: "Assembler",
        example4:"Les ouvriers se sont assemblés dans la salle",
        arabic: "اجْتَمَعَ",
        example5:"جْتَمَعَ العُمَّالُ فِي القَاعَةِ",
        id: "5-6",
      },
      {
        english: "Explore",
        example1:"They explored the city on foot",
        chinese: "探索",
        example2:"他们徒步探索这座城市",
        spanish: "Explorar",
        example3:"Ellos exploraron la ciudad a pie",
        french: "Explorer",
        example4:"Ils ont exploré la ville à pied",
        arabic: "اسْتَكْشَفَ",
        example5:"اسْتَكْشَفُوا المَدِينَةَ مَشْيًا عَلَى الأَقْدَامِ",
        id: "5-7",
      },
      {
        english: "Topic",
        example1:"Pollution is the main topic of the debate",
        chinese: "话题",
        example2:"污染是辩论的主要话题",
        spanish: "Tema",
        example3:"La contaminación es el tema principal del debate",
        french: "Sujet",
        example4:"La pollution est le sujet principal du débat",
        arabic: "مَوْضُوع",
        example5:"التَّلَوُّثُ هُوَ المَوْضُوعُ الرَّئِيسِيُّ لِلنِّقَاشِ",
        id: "5-8",
      },
      {
        english: "Debate",
        example1:"The debate lasted for two hours",
        chinese: "辩论",
        example2:"辩论持续了两个小时",
        spanish: "Debate",
        example3:"El debate duró dos horas",
        french: "Débat",
        example4:"Le débat a duré deux heures",
        arabic: "مُنَاقَشَة",
        example5:"اسْتَمَرَّ النِّقَاشُ مُدَّةَ سَاعَتَيْنِ",
        id: "5-9",
      },
      {
        english: "Evade",
        example1:"The thief tried to evade the police",
        chinese: "逃避",
        example2:"小偷试图逃避警察",
        spanish: "Evadir",
        example3:"El ladrón trató de evadir a la policía",
        french: "Eviter",
        example4:"Le voleur a essayé d’échapper à la police",
        arabic: "تَجَنَّبَ",
        example5:"حَاوَلَ اللِّصُّ أَنْ يَتَجَنَّبَ الشُّرْطَةَ",
        id: "5-10",
      },
      {
        english: "Probe",
        example1:"The detective probed the mystery",
        chinese: "探查",
        example2:"侦探调查了这个谜团",
        spanish: "Investigar",
        example3:"El detective investigó el misterio",
        french: "Sonder",
        example4:"Le détective a sondé le mystère",
        arabic: "فَحَصَ",
        example5:"بَحَثَ المُحَقِّقُ فِي اللُّغْزِ",
        id: "5-11",
      },
      {
        english: "Reform",
        example1:"The government plans to reform the law",
        chinese: "改革",
        example2:"政府计划改革法律",
        spanish: "Reforma",
        example3:"El gobierno planea reformar la ley",
        french: "Réforme",
        example4:"Le gouvernement prévoit de réformer la loi",
        arabic: "إِصْلَاح",
        example5:"تُخَطِّطُ الحُكُومَةُ لِإِصْلَاحِ القَانُونِ",
        id: "5-12",
      },
    ],
  },
      {
    id: "6",
    title: "Lesson 6",
    words: [
     {
        english: "Approach",
        example1:"A strange man approached the house",
        chinese: "接近",
        example2:"一个陌生人走近了房子",
        spanish: "Acercarse",
        example3:"Un hombre extraño se acercó a la casa",
        french: "Approche",
        example4:"Un homme étrange s’est approché de la maison",
        arabic: "اِقْتَرَبَ",
        example5:"اقْتَرَبَ رَجُلٌ غَرِيبٌ مِنَ البَيْتِ",
        id: "6-1",
      },
      {
        english: "Detect",
        example1:"The doctor detected an infection",
        chinese: "发现",
        example2:"医生发现了一种感染",
        spanish: "Detectar",
        example3:"El médico detectó una infección",
        french: "Détecter",
        example4:"Le médecin a détecté une infection",
        arabic: "كَشَفَ",
        example5:"اكْتَشَفَ الطَّبِيبُ عَدْوَى",
        id: "6-2",
      },
      {
        english: "Defect",
        example1:"The car has a serious defect in the engine",
        chinese: "缺陷",
        example2:"这辆车的发动机有一个严重的缺陷",
        spanish: "Defecto",
        example3:"El coche tiene un defecto grave en el motor",
        french: "Défaut",
        example4:"La voiture a un défaut grave dans le moteur",
        arabic: "عَيْب",
        example5:"لِلسَّيَّارَةِ عَيْبٌ خَطِيرٌ فِي المُحَرِّكِ",
        id: "6-3",
      },
      {
        english: "Employee",
        example1:"The company has many employees",
        chinese: "雇员",
        example2:"这家公司有很多员工",
        spanish: "Empleado",
        example3:"La empresa tiene muchos empleados",
        french: "Employé",
        example4:"L’entreprise a beaucoup d’employés",
        arabic: "مُوَظَّف",
        example5:"لَدَى الشَّرِكَةِ كَثِيرٌ مِنَ المُوَظَّفِينَ",
        id: "6-4",
      },
      {
        english: "Neglect",
        example1:"He neglected his garden for weeks",
        chinese: "忽视",
        example2:"他好几个星期都忽视了花园",
        spanish: "Descuidar",
        example3:"Él descuidó su jardín durante semanas",
        french: "Négliger",
        example4:"Il a négligé son jardin pendant des semaines",
        arabic: "أَهْمَلَ",
        example5:"أَهْمَلَ حَدِيقَتَهُ أَسَابِيعَ عِدَّةً",
        id: "6-5",
      },
      {
        english: "Deceive",
        example1:"She deceived him with a lie",
        chinese: "欺骗",
        example2:"她用一个谎言欺骗了他",
        spanish: "Engañar",
        example3:"Ella lo engañó con una mentira",
        french: "Tromper",
        example4:"Elle l’a trompé avec un mensonge",
        arabic: "خَدَعَ",
        example5:"خَدَعَتْهُ بِكَذِبَةٍ",
        id: "6-6",
      },
      {
        english: "Undoubtedly",
        example1:"He will undoubtedly win the prize",
        chinese: "毫无疑问地",
        example2:"他无疑会赢得奖项",
        spanish: "Indudablemente",
        example3:"Sin duda él ganará el premio",
        french: "Sans aucun doute",
        example4:"Il gagnera sans aucun doute le prix",
        arabic: "بِدُونِ شَكّ",
        example5:"سَيَفُوزُ بِالْجَائِزَةِ دُونَ شَكٍّ",
        id: "6-7",
      },
      {
        english: "Popular",
        example1:"This singer is very popular among young people",
        chinese: "受欢迎的",
        example2:"这位歌手在年轻人中非常受欢迎",
        spanish: "Popular",
        example3:"Este cantante es muy popular entre los jóvenes",
        french: "Populaire",
        example4:"Ce chanteur est très populaire parmi les jeunes",
        arabic: "شَعْبِيّ",
        example5:"هَذَا الْمُغَنِّي مَشْهُورٌ جِدًّا بَيْنَ الشَّبَابِ",
        id: "6-8",
      },
      {
        english: "Thorough",
        example1:"The police made a thorough investigation",
        chinese: "彻底的",
        example2:"警方进行了彻底的调查",
        spanish: "Minucioso",
        example3:"La policía hizo una investigación exhaustiva",
        french: "Minutieux",
        example4:"La police a mené une enquête approfondie",
        arabic: "شَامِل",
        example5:"قَامَتِ الشُّرْطَةُ بِتَحْقِيقٍ شَامِلٍ",
        id: "6-9",
      },
      {
        english: "Client",
        example1:"The lawyer met with his client",
        chinese: "客户",
        example2:"律师见了他的客户",
        spanish: "Cliente",
        example3:"El abogado se reunió con su cliente",
        french: "Client",
        example4:"L’avocat a rencontré son client",
        arabic: "عَمِيل",
        example5:"قَابَلَ المُحَامِي زَبُونَهُ",
        id: "6-10",
      },
      {
        english: "Comprehensive",
        example1:"I cannot comprehend this difficult text",
        chinese: "全面的",
        example2:"我无法理解这篇困难的文章",
        spanish: "Comprensivo",
        example3:"No puedo comprender este texto difícil",
        french: "Complet",
        example4:"Je ne peux pas comprendre ce texte difficile",
        arabic: "شَامِل",
        example5:"لَا أَسْتَطِيعُ أَنْ أَسْتَوْعِبَ هَذَا النَّصَّ الصَّعْبَ",
        id: "6-11",
      },
      {
        english: "Defraud",
        example1:"The man tried to defraud the bank",
        chinese: "欺诈",
        example2:"那个人试图诈骗银行",
        spanish: "Defraudar",
        example3:"El hombre intentó estafar al banco",
        french: "Escroquer",
        example4:"L’homme a essayé de frauder la banque",
        arabic: "اِحْتَالَ",
        example5:"حَاوَلَ الرَّجُلُ أَنْ يَحْتَالَ عَلَى المَصْرِفِ",
        id: "6-12",
      },
    ],
  },
  {
    id: "7",
    title: "Lesson 7",
    words: [
      {
        english: "Postpone",
        chinese: "推迟",
        spanish: "Posponer",
        french: "Reporter",
        arabic: "أَجَّلَ",
        id: "7-1",
      },
      {
        english: "Consent",
        chinese: "同意",
        spanish: "Consentir",
        french: "Consentir",
        arabic: "مُوَافَقَة",
        id: "7-2",
      },
      {
        english: "Massive",
        chinese: "巨大的",
        spanish: "Masivo",
        french: "Massif",
        arabic: "ضَخْم",
        id: "7-3",
      },
      {
        english: "Capsule",
        chinese: "胶囊",
        spanish: "Cápsula",
        french: "Capsule",
        arabic: "كَبْسُولَة",
        id: "7-4",
      },
      {
        english: "Preserve",
        chinese: "保存",
        spanish: "Preservar",
        french: "Préserver",
        arabic: "حَفِظَ",
        id: "7-5",
      },
      {
        english: "Denounce",
        chinese: "谴责",
        spanish: "Denunciar",
        french: "Dénoncer",
        arabic: "شَجَبَ",
        id: "7-6",
      },
      {
        english: "Unique",
        chinese: "独特的",
        spanish: "Unico",
        french: "Unique",
        arabic: "فَرِيد",
        id: "7-7",
      },
      {
        english: "Torrent",
        chinese: "急流",
        spanish: "Torrente",
        french: "Torrent",
        arabic: "سَيْل جَارِف",
        id: "7-8",
      },
      {
        english: "Resent",
        chinese: "怨恨",
        spanish: "Resentir",
        french: "En vouloir à",
        arabic: "سَخِطَ",
        id: "7-9",
      },
      {
        english: "Molest",
        chinese: "骚扰",
        spanish: "Molestar",
        french: "Importuner",
        arabic: "تَحَرَّشَ",
        id: "7-10",
      },
      {
        english: "Gloomy",
        chinese: "阴郁的",
        spanish: "Sombrío",
        french: "Sombre",
        arabic: "كَئِيب",
        id: "7-11",
      },
      {
        english: "Unforeseen",
        chinese: "出乎意料的",
        spanish: "Imprevisto",
        french: "Imprévu",
        arabic: "غَيْر مُتَوَقَّع",
        id: "7-12",
      },
    ],
  },
];









